const medicines=[
{id:1,name:"Dolo 650",salt:"Paracetamol 650 mg",price:15,rx:false,cat:"Fever & Pain"},
{id:2,name:"Azithral 500",salt:"Azithromycin 500 mg",price:75,rx:true,cat:"Prescription"},
{id:3,name:"Shelcal 500",salt:"Calcium + Vitamin D3",price:120,rx:false,cat:"Vitamins"},
{id:4,name:"Glycomet 500",salt:"Metformin 500 mg",price:45,rx:true,cat:"Diabetes"},
{id:5,name:"Amlodipine 5 mg",salt:"Amlodipine",price:25,rx:true,cat:"Heart Care"},
{id:6,name:"Limcee",salt:"Vitamin C 500 mg",price:30,rx:false,cat:"Vitamins"},
{id:7,name:"Cetirizine",salt:"Cetirizine 10 mg",price:22,rx:false,cat:"Allergy"},
{id:8,name:"Pantop 40",salt:"Pantoprazole 40 mg",price:86,rx:true,cat:"Digestive Care"},
{id:9,name:"ORS Sachet",salt:"Oral Rehydration Salts",price:24,rx:false,cat:"General Care"}
];
const doctors=[
{name:"Dr. Rohan Sharma",specialty:"General Physician",degree:"MBBS, MD",exp:"9 years",rating:"4.8",fee:299,emoji:"👨‍⚕️"},
{name:"Dr. Neha Verma",specialty:"Gynecologist",degree:"MBBS, MS",exp:"8 years",rating:"4.7",fee:399,emoji:"👩‍⚕️"},
{name:"Dr. Amit Jain",specialty:"Dermatologist",degree:"MBBS, MD",exp:"6 years",rating:"4.6",fee:349,emoji:"👨‍⚕️"},
{name:"Dr. Priya Nair",specialty:"Pediatrician",degree:"MBBS, DCH",exp:"10 years",rating:"4.9",fee:399,emoji:"👩‍⚕️"},
{name:"Dr. Arjun Mehta",specialty:"Orthopedic",degree:"MBBS, MS Ortho",exp:"12 years",rating:"4.8",fee:499,emoji:"👨‍⚕️"},
{name:"Dr. Sana Khan",specialty:"Mental Wellness",degree:"MD Psychiatry",exp:"7 years",rating:"4.9",fee:549,emoji:"👩‍⚕️"}
];
const labs=[
{name:"Full Body Basic",tests:"CBC, LFT, KFT, Lipid, Sugar",price:799,time:"Reports in 24 hrs"},
{name:"Diabetes Care",tests:"HbA1c, FBS, PPBS",price:499,time:"Reports in 12 hrs"},
{name:"Thyroid Profile",tests:"T3, T4, TSH",price:399,time:"Reports in 18 hrs"},
{name:"Heart Health",tests:"Lipid, hs-CRP, ECG booking",price:999,time:"Reports in 24 hrs"}
];
let cart=JSON.parse(localStorage.getItem("satiMedicsCart")||"[]");
let activeView="home";
const view=document.getElementById("view");

function money(n){return "₹"+n.toFixed(0)}
function saveCart(){localStorage.setItem("satiMedicsCart",JSON.stringify(cart));updateCartCount()}
function updateCartCount(){document.getElementById("cartCount").textContent=cart.reduce((a,b)=>a+b.qty,0)}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function setActiveNav(name){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.nav===name))}
function nav(name,data={}){activeView=name;setActiveNav(name);window.scrollTo({top:0,behavior:"smooth"});
 if(name==="home")renderHome(); if(name==="medicines")renderMedicines(data.query||""); if(name==="consult")renderConsult(data.specialty||"");
 if(name==="labs")renderLabs(); if(name==="prescription")renderPrescription(); if(name==="cart")renderCart(); if(name==="orders")renderOrders(); if(name==="profile")renderProfile();
}

function renderHome(){const tpl=document.getElementById("homeTemplate").content.cloneNode(true);view.innerHTML="";view.appendChild(tpl);
 document.getElementById("globalSearchBtn").onclick=()=>{const q=document.getElementById("globalSearch").value.trim(); if(q)nav("medicines",{query:q});};
 document.getElementById("globalSearch").addEventListener("keydown",e=>{if(e.key==="Enter")document.getElementById("globalSearchBtn").click()});
 document.querySelectorAll("[data-specialty]").forEach(b=>b.onclick=()=>nav("consult",{specialty:b.dataset.specialty}));
 attachNav();
}

function renderMedicines(query=""){setActiveNav("medicines");view.innerHTML=`<section class="page"><span class="eyebrow">MEDICINE DELIVERY</span><h1 style="font-size:38px;margin:8px 0 6px">Order medicines</h1><p style="color:var(--muted)">Browse common medicines. Prescription medicines require pharmacist verification.</p>
<div class="toolbar"><input id="medSearch" placeholder="Search medicine or salt..." value="${query.replaceAll('"','&quot;')}"><select id="catFilter"><option>All categories</option>${[...new Set(medicines.map(m=>m.cat))].map(c=>`<option>${c}</option>`).join("")}</select></div><div class="product-grid" id="productGrid"></div></section>`;
 const draw=()=>{const q=document.getElementById("medSearch").value.toLowerCase(),cat=document.getElementById("catFilter").value;const list=medicines.filter(m=>(m.name+" "+m.salt).toLowerCase().includes(q)&&(cat==="All categories"||m.cat===cat));document.getElementById("productGrid").innerHTML=list.map(m=>`<article class="card"><div class="product-image">💊</div><div style="margin-top:12px"><span class="badge">${m.rx?"Prescription required":"OTC / wellness"}</span><h3>${m.name}</h3><small>${m.salt}</small></div><div class="price-row"><span class="price">${money(m.price)}</span><button class="pill-btn" data-add="${m.id}">Add +</button></div></article>`).join("")||'<div class="empty">No medicines found.</div>';document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addToCart(+b.dataset.add))};
 draw();document.getElementById("medSearch").oninput=draw;document.getElementById("catFilter").onchange=draw;
}
function addToCart(id){const m=medicines.find(x=>x.id===id),row=cart.find(x=>x.id===id);if(row)row.qty++;else cart.push({...m,qty:1});saveCart();toast(m.name+" added to cart")}

function renderConsult(specialty=""){setActiveNav("consult");view.innerHTML=`<section class="page"><span class="eyebrow">DOCTOR CONSULTATION</span><h1 style="font-size:38px;margin:8px 0 6px">Consult verified doctors</h1><p style="color:var(--muted)">Demo doctor profiles for product experience. Production onboarding should include license and credential verification.</p><div class="toolbar"><select id="docFilter"><option>All specialties</option>${[...new Set(doctors.map(d=>d.specialty))].map(s=>`<option ${s===specialty?"selected":""}>${s}</option>`).join("")}</select></div><div class="doctor-grid" id="doctorGrid"></div></section>`;
 const draw=()=>{const f=document.getElementById("docFilter").value;const list=doctors.filter(d=>f==="All specialties"||d.specialty===f);document.getElementById("doctorGrid").innerHTML=list.map((d,i)=>`<article class="card"><div class="doctor-head"><div class="doctor-avatar">${d.emoji}</div><div><h3>${d.name}</h3><small>${d.specialty}</small></div></div><p>${d.degree} • ${d.exp}</p><div class="rating">★ ${d.rating} verified patient rating</div><div class="price-row"><span class="price">${money(d.fee)}</span><button class="pill-btn" data-book="${doctors.indexOf(d)}">Consult now</button></div></article>`).join("");document.querySelectorAll("[data-book]").forEach(b=>b.onclick=()=>renderBooking(doctors[+b.dataset.book]))};draw();document.getElementById("docFilter").onchange=draw;
}
function renderBooking(doc){view.innerHTML=`<section class="page"><button class="outline-btn" onclick="nav('consult')">← Back</button><div class="consult-panel" style="margin-top:16px"><div class="consult-form"><span class="eyebrow">BOOK CONSULTATION</span><h2 style="margin:8px 0 20px">${doc.name} • ${doc.specialty}</h2><div class="form-grid"><input id="patientName" placeholder="Patient name"><input id="patientAge" type="number" placeholder="Age"><select id="mode"><option>Video consultation</option><option>Audio consultation</option><option>Chat consultation</option></select><input id="slot" type="datetime-local"><textarea id="symptoms" rows="5" placeholder="Describe symptoms / concern"></textarea><button class="primary-btn" id="confirmConsult">Confirm consultation • ${money(doc.fee)}</button></div></div><div class="video-mock"><div class="video-screen"><div><div class="avatar">${doc.emoji}</div><h2 style="color:white">${doc.name}</h2><p>Secure consultation room preview</p><p style="opacity:.65;font-size:12px">Camera and call services require production telemedicine integration.</p></div></div></div></div></section>`;document.getElementById("confirmConsult").onclick=()=>{if(!document.getElementById("patientName").value||!document.getElementById("slot").value)return toast("Add patient name and slot");localStorage.setItem("satiMedicsConsult",JSON.stringify({doctor:doc.name,specialty:doc.specialty,slot:document.getElementById("slot").value}));toast("Consultation booked");setTimeout(()=>nav("orders"),700)}}
function renderLabs(){view.innerHTML=`<section class="page"><span class="eyebrow">DIAGNOSTICS</span><h1 style="font-size:38px;margin:8px 0 6px">Lab tests at home</h1><p style="color:var(--muted)">Book sample collection from your home. Availability varies by city.</p><div class="lab-grid" style="margin-top:22px">${labs.map((l,i)=>`<article class="card"><div class="product-image">🧪</div><h3>${l.name}</h3><p>${l.tests}</p><small>${l.time}</small><div class="price-row"><span class="price">${money(l.price)}</span><button class="pill-btn" data-lab="${i}">Book test</button></div></article>`).join("")}</div></section>`;document.querySelectorAll("[data-lab]").forEach(b=>b.onclick=()=>{localStorage.setItem("satiMedicsLab",JSON.stringify(labs[+b.dataset.lab]));toast("Lab package added to bookings")})}
function renderPrescription(){view.innerHTML=`<section class="page"><span class="eyebrow">PRESCRIPTION ORDER</span><h1 style="font-size:38px;margin:8px 0 6px">Upload prescription</h1><div class="section-block" style="max-width:700px"><p>Upload a clear image/PDF. In production, a licensed pharmacist should review prescription-only medicines before fulfilment.</p><div class="form-grid"><input id="rxFile" type="file" accept="image/*,.pdf"><textarea id="rxNote" rows="4" placeholder="Optional note for pharmacist"></textarea><button class="primary-btn" id="submitRx">Submit for review</button></div></div></section>`;document.getElementById("submitRx").onclick=()=>{if(!document.getElementById("rxFile").files.length)return toast("Please choose a prescription file");toast("Prescription submitted for pharmacist review")}}
function renderCart(){view.innerHTML=`<section class="page"><span class="eyebrow">YOUR CART</span><h1 style="font-size:38px;margin:8px 0 20px">Medicine cart</h1><div id="cartBody"></div></section>`;drawCart()}
function drawCart(){const body=document.getElementById("cartBody");if(!cart.length){body.innerHTML='<div class="empty"><div style="font-size:48px">🛒</div><h2>Your cart is empty</h2><p>Add medicines to continue.</p><button class="primary-btn" onclick="nav(\'medicines\')">Browse medicines</button></div>';return}
 const total=cart.reduce((a,b)=>a+b.price*b.qty,0);body.innerHTML=`<div class="cart-list">${cart.map((m,i)=>`<div class="cart-item"><div><strong>${m.name}</strong><small style="display:block">${m.salt}</small></div><div style="display:flex;align-items:center;gap:10px"><button class="outline-btn" data-minus="${i}">−</button><strong>${m.qty}</strong><button class="outline-btn" data-plus="${i}">+</button><strong style="min-width:58px">${money(m.price*m.qty)}</strong></div></div>`).join("")}</div><div class="section-block"><div class="price-row"><div><small>Estimated total</small><h2>${money(total)}</h2></div><button class="primary-btn" id="checkoutBtn">Proceed to delivery</button></div></div>`;document.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>{const i=+b.dataset.minus;cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);saveCart();drawCart()});document.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qty++;saveCart();drawCart()});document.getElementById("checkoutBtn").onclick=renderCheckout}
function renderCheckout(){view.innerHTML=`<section class="page"><button class="outline-btn" onclick="nav('cart')">← Back</button><div class="section-block" style="max-width:720px;margin-top:16px"><span class="eyebrow">DELIVERY DETAILS</span><h2 style="margin:8px 0 20px">Where should we deliver?</h2><div class="form-grid"><input id="custName" placeholder="Full name"><input id="phone" placeholder="Mobile number"><textarea id="address" rows="4" placeholder="Full delivery address"></textarea><select id="pay"><option>Cash on delivery</option><option>UPI on delivery</option><option>Online payment (integration required)</option></select><button class="primary-btn" id="placeOrder">Place demo order</button></div></div></section>`;document.getElementById("placeOrder").onclick=()=>{if(!document.getElementById("custName").value||!document.getElementById("phone").value||!document.getElementById("address").value)return toast("Fill all delivery details");const order={id:"SM"+Date.now().toString().slice(-6),time:new Date().toISOString(),items:cart,status:2,city:document.getElementById("citySelect").value};localStorage.setItem("satiMedicsOrder",JSON.stringify(order));cart=[];saveCart();toast("Order placed successfully");setTimeout(()=>nav("orders"),700)}}
function renderOrders(){setActiveNav("orders");const order=JSON.parse(localStorage.getItem("satiMedicsOrder")||"null"),consult=JSON.parse(localStorage.getItem("satiMedicsConsult")||"null");view.innerHTML=`<section class="page"><span class="eyebrow">ACTIVITY</span><h1 style="font-size:38px;margin:8px 0 20px">Orders & appointments</h1>${order?`<div class="section-block"><div class="section-title"><div><span class="badge">Order #${order.id}</span><h2>Arriving soon</h2><p style="color:var(--muted)">Delivery in ${order.city}</p></div><span style="font-size:42px">🛵</span></div><div class="timeline">${["Order confirmed","Packed at pharmacy","Out for delivery","Delivered"].map((s,i)=>`<div class="timeline-step ${i<=order.status?"done":""}"><div class="timeline-dot">${i<=order.status?"✓":i+1}</div><div><strong>${s}</strong><small style="display:block;color:var(--muted);margin-top:4px">${i<=order.status?"Completed":"Pending"}</small></div></div>`).join("")}</div></div>`:'<div class="empty"><h2>No medicine orders yet</h2><button class="primary-btn" onclick="nav(\'medicines\')">Order medicines</button></div>'}${consult?`<div class="section-block"><span class="badge">Doctor consultation</span><h2 style="margin-top:10px">${consult.doctor}</h2><p>${consult.specialty} • ${new Date(consult.slot).toLocaleString()}</p></div>`:""}</section>`}

function renderProfile(){setActiveNav("profile");view.innerHTML=`<section class="page"><span class="eyebrow">ACCOUNT</span><h1 style="font-size:38px;margin:8px 0 20px">My health profile</h1><div class="profile-grid"><div class="profile-card"><div class="profile-hero"><div class="profile-avatar">👤</div><div><h2>Guest User</h2><p style="color:var(--muted)">Create your profile to save addresses, reports and family members.</p></div></div><div class="program-grid" style="margin-top:20px"><article><span>👨‍👩‍👧</span><div><strong>Family profiles</strong><small>Manage care for parents & children</small></div></article><article><span>📄</span><div><strong>Health records</strong><small>Prescriptions and reports</small></div></article><article><span>🔁</span><div><strong>Refill reminders</strong><small>Never miss routine medicines</small></div></article></div></div><div class="settings-card"><h2>Settings</h2><div class="settings-list"><button>📍 Saved addresses</button><button>🌐 Language: English / हिन्दी</button><button>🔒 Privacy & security</button><button>☎️ Help & support</button><button>ℹ️ About Sati Medics</button></div></div></div></section>`}

function attachNav(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>nav(b.dataset.nav))}
document.addEventListener("click",e=>{const b=e.target.closest("[data-nav]");if(b&& !b.classList.contains("nav-item"))nav(b.dataset.nav)})
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>nav(b.dataset.nav));
document.getElementById("notificationBtn").onclick=()=>toast("No new notifications");
document.getElementById("citySelect").onchange=e=>toast("Service city changed to "+e.target.value);
updateCartCount();renderHome();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
